In [3]:
def add_numbers(x,y):
    return (x+y)
    
add_numbers(5,8)    

13

In [5]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(10,22)

32

In [6]:
type(None) #returns type of the specified value

NoneType

In [7]:
type(1.0)

float

In [8]:
type(add_numbers)

function

In [9]:
tup=(1,'a',2.5,'f')
type(tup)

tuple

In [10]:
lst=[1,'a',2.5,'f']
type(lst)

list

In [11]:
lst.append(3.7) #append an element to list. list is mutable object in python

In [13]:
for i in lst: # loop to iterate items in the list
    print(i)

1
a
2.5
f
3.7


In [15]:
length= len(lst) #calculate length of the list
print(length)

5


In [19]:
for i in range(len(lst)):
    print(lst[i])

1
a
2.5
f
3.7


In [20]:
lst2=[3,'f',3.5,'z']
print(lst+lst2) # concatenates list1 and list2

[1, 'a', 2.5, 'f', 3.7, 3, 'f', 3.5, 'z']


In [21]:
print(lst*3) # prints the list 3 times

[1, 'a', 2.5, 'f', 3.7, 1, 'a', 2.5, 'f', 3.7, 1, 'a', 2.5, 'f', 3.7]


<br>
Slicing operations

In [23]:
str= "Ketaki is learning Data Science"
print(len(str))

31


In [24]:
str[-1]

'e'

In [25]:
str[4:]

'ki is learning Data Science'

In [27]:
str[-7:-2]

'Scien'

In [28]:
str[:4]

'Keta'

<br>
Split

In [31]:
firstname = 'Ketaki is learning Data Science'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Ketaki is learning Data Science'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

Ketaki
Science


<br>

<br>
Learning dictionaries

In [41]:
dict = {'Name':'Ketaki','email':'k.ketaki28@gmail.com'}
print(dict)
for i in dict.items(): #iterates over all of the items
    print(i)
    
for i in dict.values():# iterates over the values
    print(i)
    
for i in dict:     #iterates over the keys
    print(i)


{'Name': 'Ketaki', 'email': 'k.ketaki28@gmail.com'}
('Name', 'Ketaki')
('email', 'k.ketaki28@gmail.com')
Ketaki
k.ketaki28@gmail.com
Name
email


In [45]:
#unpack sequence into various variables:
tup = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = tup
for i in tup:
    print(i)



Christopher
Brooks
brooksch@umich.edu


<br>
String formatting using in built python function

In [63]:
sales_format = {'price':3.24,
                'qty':4,
                'Name':'Ketaki'
}
sales_dict = {'price':5.24,'qty':10,'Name':'Sumit'}
sales_format.update(sales_dict)

for i in sales_format:
    print(sales_format[i])

sales_statement='{} bought {} apples at total price of {}'
print(sales_statement.format(sales_format['Name'],sales_format['qty'],sales_format['price']*sales_format['qty']))

5.24
10
Sumit
Sumit bought 10 apples at total price of 52.400000000000006


In [78]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile)) #csv.Dictreader has read in each row of our csv file as a dictionary and then we 
                                        #conversted it to a list and assigned it to mpg
    
mpg[:3] # The first three dictionaries in our list.

#len(mpg) #gives no of entries=234

mpg[0].keys() # keys gives us column names of the csv

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

In [92]:
# now we have to calculate city mpg (cty column) and highway mpg (hwy column) for all cars

length= len(mpg)
addn_cty= sum(float(d['cty']) for d in mpg)
addn_hwy = sum(float(d['hwy']) for d in mpg)
    
avg_cty=addn_cty/length
avg_hwy=addn_hwy/length
print(avg_cty)
print(avg_hwy)

16.858974358974358
23.44017094017094


<br><b>
Use set to return the unique values for the number of cylinders the cars in our dataset have.

In [93]:
cylinders = set(d['cyl'] for d in mpg) #gives unique values under number of cylinders column from data set
cylinders

{'4', '5', '6', '8'}

<b>grouping the cars by number of cylinder, and finding the average cty mpg for each group.

In [96]:
CtyMpgByCyl=[]
for i in cylinders:
    print(i)
    summpg=0
    count=0
    for d in mpg:
        if d['cyl']==i:
            summpg= summpg+float(d['cty'])
            count=count+1
    CtyMpgByCyl.append((i,summpg/count)) # for appending tuple ('no of cyl','city avg')
    
CtyMpgByCyl.sort(key=lambda x: x[0]) # sorting the tuple
CtyMpgByCyl    
    
    
        

4
5
6
8


[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

<b>how to find the average hwy mpg for each class of vehicle in our dataset.

In [95]:
vehicles_class=set(d['class'] for d in mpg) # lists unique type of vehicles class
vehicles_class

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

In [99]:
vehicles_class=set(d['class'] for d in mpg) # lists unique type of vehicles class
HwyMpgByCls=[]
for i in vehicles_class:
    summpg=0
    count=0
    for d in mpg:
        if d['class']==i:
            summpg=summpg+float(d['hwy'])
            count=count+1
    HwyMpgByCls.append((i,summpg/count))
    
HwyMpgByCls.sort(key=lambda x:x[0])    
HwyMpgByCls

[('2seater', 24.80),
 ('compact', 28.30),
 ('midsize', 27.29),
 ('minivan', 22.36),
 ('pickup', 16.88),
 ('subcompact', 28.14),
 ('suv', 18.13)]

# Learning dates and times

In [103]:
import datetime as dt
import time as tm

dtnow=dt.datetime.fromtimestamp(tm.time()) #convert timestamp to datetime
dtnow

datetime.datetime(2019, 4, 8, 0, 25, 16, 844546)

In [104]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2019, 4, 8, 0, 25, 16)

In [111]:
#timedelta is a duration expressing the difference between two dates.
delta = dt.timedelta(days = 5) # create a timedelta of 100 days
delta

datetime.timedelta(5)

In [110]:
#returns todays date
today=dt.date.today()
today

datetime.date(2019, 4, 8)

In [112]:
today-delta #date 5 days ago

datetime.date(2019, 4, 3)

In [113]:
today> today+delta

False

# CLASS

In [116]:
class Person():
    department='Computer Science'
    
    def set_name(self,new_name):
        self.name=new_name
        
    def set_loc(self,new_loc):
        self.loc=new_loc
        
person = Person()
person.set_name('Ketaki')
person.set_loc('Texas')
print('{} lives in {} and works for {} department'.format(person.name,person.loc,person.department))

Ketaki lives in Texas and works for Computer Science department


In [119]:
#mapping min function between 2 lists
store1 = [10.00, 11.00, 12.34, 2.01]
store2 = [9.00, 11.10, 12.34, 2.04]
cheapest = map(min, store1, store2)

for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


In [124]:
import numpy as np
test = np.random.randint(0, 10, (4,3))
for row in test:
    print(row)

[3 5 5]
[3 3 2]
[9 5 2]
[4 4 5]


In [125]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [128]:
m = np.array([[[7,8,9],[1,2,3]],[[0,1,2],[4,5,6]],[[7,4,5],[1,4,9]]])
m

array([[[7, 8, 9],
        [1, 2, 3]],

       [[0, 1, 2],
        [4, 5, 6]],

       [[7, 4, 5],
        [1, 4, 9]]])